Given a neuroscientific paper, our goal is to:
- extract connections
- extract parthood relations

In [1]:
import pathlib

for path in ['progress', 'networks']:
    pathlib.Path(path).mkdir(exist_ok=True)

In [2]:
from pyvis.network import Network
import ipywidgets as widgets

In [3]:
net = Network(directed=True, notebook=True)

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.

In [4]:
node_name = widgets.Text(placeholder='nazwa')
node_abbr = widgets.Text(placeholder='skrót')
button = widgets.Button(description='Dodaj')

def add_structure(b):
    name = node_name.value
    abbr = node_abbr.value
    
    net.add_node(abbr, label=abbr, title=name)
    
    node_name.value = ''
    node_abbr.value = ''

button.on_click(add_structure)

node_box = widgets.Box(children=[
    widgets.Label('Struktura'),
    node_name,
    node_abbr,
    button
])
node_box

Box(children=(Label(value='Struktura'), Text(value='', placeholder='nazwa'), Text(value='', placeholder='skrót…

In [5]:
# Add a few nodes programatically for the sake of presentation
new_nodes = [
        {'title': 'piriform cortex', 'id': 'PC', 'label': 'PC'},
        {'title': 'olfactory bulb', 'id': 'OB', 'label': 'OB'},
        {'title': 'ventral tegmental area', 'id': 'VTA', 'label': 'VTA'},
        {'title': 'nucleus accumbens', 'id': 'NAc', 'label': 'NAc'},
        {'title': 'ventral pallidum', 'id': 'VP', 'label': 'VP'},
        {'title': 'paraventricular thalamus', 'id': 'PVT', 'label': 'PVT'},
        {'title': 'olfactory tubercle', 'id': 'OT', 'label': 'OT'},
        {'title': 'anterior olfactory nucleus', 'id': 'AON', 'label': 'AON'},
        {'title': 'mediodorsal thalamus', 'id': 'MDT', 'label': 'MDT'}
]
for node in new_nodes:
   net.add_node(node['id'], label=node['label'], title=node['title'])

In [6]:
net.show('networks/MVP_nodes.html')

networks/MVP_nodes.html

In [7]:
fro = widgets.Text(placeholder='A')
to = widgets.Text(placeholder='B')
doi = widgets.Text(placeholder='DOI')
sentence = widgets.Text(placeholder='Zdanie źródłowe')

In [8]:
button = widgets.Button(description='Połącz')

def add_edge(b):
    net.add_edge(
        fro.value,
        to.value,
        title=(doi.value + '\n' + sentence.value))
    
    fro.value = ''
    to.value = ''
    sentence.value = ''

button.on_click(add_edge)

In [9]:
nodes = [fro, widgets.Label(value=' → '), to]
nodes_layout = widgets.Layout(display='flex',
                            flex_flow='row',
                            align_items='stretch')
nodes_box = widgets.Box(children=nodes, layout=nodes_layout)

items = [nodes_box, doi, sentence, button]
box_layout = widgets.Layout(display='flex',
                    flex_flow='column', 
                    align_items='stretch',
                    width='600px',
                    overflow='hidden')

box = widgets.Box(children=items, layout=box_layout)
box

Box(children=(Box(children=(Text(value='', placeholder='A'), Label(value=' → '), Text(value='', placeholder='B…

In [10]:
# Add a few edges
new_edges = [
    {'from': 'OT', 'to': 'VP', 'doi': 'https://doi.org/10.3389/fncir.2024.1423505', 'sentence': 'the major output from the OT is considered to the ventral pallidum (VP)'},
    {'from': 'OT', 'to': 'AON', 'doi': 'https://doi.org/10.3389/fncir.2024.1423505', 'sentence': 'Many recent studies, including those employing transsynaptic tracing, have revealed various projection targets of the OT, including the [...] anterior olfactory nucleus'},
    {'from': 'OT', 'to': 'PC', 'doi': 'https://doi.org/10.3389/fncir.2024.1423505', 'sentence': 'Many recent studies, including those employing transsynaptic tracing, have revealed various projection targets of the OT, including the PC'},
    {'from': 'OT', 'to': 'MDT', 'doi': 'https://doi.org/10.3389/fncir.2024.1423505', 'sentence': 'Many recent studies, including those employing transsynaptic tracing, have revealed various projection targets of the OT, including the [...] mediodorsal thalamus'},
    {'from': 'OT', 'to': 'VTA', 'doi': 'https://doi.org/10.3389/fncir.2024.1423505', 'sentence': 'Many recent studies, including those employing transsynaptic tracing, have revealed various projection targets of the OT, including the [...] VTA'}
]
for edge in new_edges:
    net.add_edge(edge['from'], edge['to'], title=(edge['doi'] + '\n' + edge['sentence']))

In [11]:
net.show('networks/MVP_network.html')

networks/MVP_network.html

In [12]:
from utils import dump_nodes, dump_edges, show_full_labels, show_abbr_labels

In [13]:
nodes = dump_nodes(net)
edges = dump_edges(net)
nodes.to_json('progress/nodes-MVP.json')
edges.to_json('progress/edges-MVP.json')

In [14]:
from IPython.display import display

display(nodes, edges)

     color                       title   id label shape
0  #97c2fc             piriform cortex   PC    PC   dot
1  #97c2fc              olfactory bulb   OB    OB   dot
2  #97c2fc      ventral tegmental area  VTA   VTA   dot
3  #97c2fc           nucleus accumbens  NAc   NAc   dot
4  #97c2fc            ventral pallidum   VP    VP   dot
5  #97c2fc    paraventricular thalamus  PVT   PVT   dot
6  #97c2fc          olfactory tubercle   OT    OT   dot
7  #97c2fc  anterior olfactory nucleus  AON   AON   dot
8  #97c2fc        mediodorsal thalamus  MDT   MDT   dot

                                               title from   to arrows
0  https://doi.org/10.3389/fncir.2024.1423505\nth...   OT   VP     to
1  https://doi.org/10.3389/fncir.2024.1423505\nMa...   OT  AON     to
2  https://doi.org/10.3389/fncir.2024.1423505\nMa...   OT   PC     to
3  https://doi.org/10.3389/fncir.2024.1423505\nMa...   OT  MDT     to
4  https://doi.org/10.3389/fncir.2024.1423505\nMa...   OT  VTA     to